#ifndef AUTOWARE_AUTO_PLANNING_MSGS__VISIBILITY_CONTROL_H_
#define AUTOWARE_AUTO_PLANNING_MSGS__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define AUTOWARE_AUTO_PLANNING_MSGS_EXPORT __attribute__ ((dllexport))
    #define AUTOWARE_AUTO_PLANNING_MSGS_IMPORT __attribute__ ((dllimport))
  #else
    #define AUTOWARE_AUTO_PLANNING_MSGS_EXPORT __declspec(dllexport)
    #define AUTOWARE_AUTO_PLANNING_MSGS_IMPORT __declspec(dllimport)
  #endif
  #ifdef AUTOWARE_AUTO_PLANNING_MSGS_BUILDING_LIBRARY
    #define AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC AUTOWARE_AUTO_PLANNING_MSGS_EXPORT
  #else
    #define AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC AUTOWARE_AUTO_PLANNING_MSGS_IMPORT
  #endif
  #define AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC_TYPE AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC
  #define AUTOWARE_AUTO_PLANNING_MSGS_LOCAL
#else
  #define AUTOWARE_AUTO_PLANNING_MSGS_EXPORT __attribute__ ((visibility("default")))
  #define AUTOWARE_AUTO_PLANNING_MSGS_IMPORT
  #if __GNUC__ >= 4
    #define AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC __attribute__ ((visibility("default")))
    #define AUTOWARE_AUTO_PLANNING_MSGS_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC
    #define AUTOWARE_AUTO_PLANNING_MSGS_LOCAL
  #endif
  #define AUTOWARE_AUTO_PLANNING_MSGS_PUBLIC_TYPE
#endif
#endif  // AUTOWARE_AUTO_PLANNING_MSGS__VISIBILITY_CONTROL_H_
// Generated 30-Oct-2025 23:01:18
 